version: '3.8'

services:
  oyun-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: sifre123
      POSTGRES_DB: oyun_veritabani
      POSTGRES_USER: oyun_admin
    ports:
      - "27018:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
